### Health Check
GET http://auth-service:3001/health


### Register User
POST http://auth-service:3001/register
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}


### Login User
POST http://auth-service:3001/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}