### Health Check
GET http://user-service:3002/health


### Get User
GET http://user-service:3002/users/1


### Update User
PUT http://user-service:3002/users/1
Content-Type: application/json

{
  "name": "updated-user"
}